# -*- coding: utf-8 -*-
"""news(using crew).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FrfMD6l6gn8DgOeahkU608mhX5_NKO7S
"""

pip install -qU langchain-google-genai

from google.colab import userdata
userdata.get('GEMINI_API')

pip install crewai

pip install 'crewai[tools]'

pip install firecrawl-py

from google.colab import userdata
SEARCH_API_KEY = userdata.get('FIRECRAWL_API_KEY')

from crewai import Agent, Task, Crew, LLM
import os

# === Define API Keys (Replace with your real keys or use environment variables) ===
GEMINI_API = "AIzaSyA-wYNWKWqxKbbnc1zL7oXR8UDhtiXLrjw"
from crewai_tools import(
    FirecrawlSearchTool
)
search_tool=FirecrawlSearchTool(api_key=SEARCH_API_KEY)
researcher=Agent(
    role="current affairs Researcher",
    goal="fetch top 5 current global news topics",
    backstory="an expert news researcher with access to latest information.",
    tools=[search_tool],
    llm=LLM(model="gemini/gemini-2.0-flash",api_key=GEMINI_API)
)
summarizer=Agent(
    role="Note Maker",
    goal="convert research into clear,short bullet points",
    backstory="an expert in simplyfying complex topics for fast reading.",
    llm=LLM(model="gemini/gemini-2.0-flash",api_key=GEMINI_API)
)
task1=Task(
    description="search for the top 5 global news stories using the web.",
    expected_output="top 5 global news stories and its details",
    agent=researcher
)
task2=Task(
    description="take the news articles from previous task and write clear 1-line summarises for each.",
    expected_output="summarised and consumable notes",
    agent=summarizer,
    context=[task1] # Explicitly pass task1 as context to task2
)
crew=Crew(
    agents=[researcher,summarizer],
    tasks=[task1,task2],
    process="sequential"
)
print(crew.kickoff())

